name: "Build iOS app"

# on: [push]
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          wget -O archive.zip "YOURLINKHERE"
          unzip archive.zip -d .

          xcodebuild archive -project Example-Project.xcodeproj -scheme 'Example-Project' -archivePath Example-Project.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv Example-Project.xcarchive/Products/Applications/Example-Project.app Payload/Example-Project.app

          zip -r "Example-Project.ipa" "Payload"

          mv Example-Project.ipa ${{ runner.temp }}/Example-Project.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: Example-Project
          path: ${{ runner.temp }}/Example-Project.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3